routes/web.php
<?php

use App\Http\Controllers\AnalyticController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\RentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('inventories/available', [RentController::class, 'getAvailableInventoriesAjax'])->name('inventories.available');

Route::resource('employees', EmployeeController::class);
Route::resource('clients', ClientController::class);
Route::resource('inventories', InventoryController::class);
Route::resource('rents', RentController::class);

Route::get('analytic/rents', [AnalyticController::class, 'rents'])->name('analytic.rents');
Route::get('analytic/employees', [AnalyticController::class, 'employees'])->name('analytic.employees');

app/Models/Inventory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Inventory extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'price_per_day',
        'price_per_week'
    ];

    public function rents() :HasMany
    {
        return $this->hasMany(Rent::class, 'inventory_id');
    }

    public function getStatusAttribute()
    {
        $activeRent = $this->rents()->where('status', 'active')
            ->first();

        return $activeRent ? 'in_rent' : 'free';
    }

}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Inventory;
use Illuminate\Http\Request;

class InventoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $inventories = Inventory::all();
        return view('inventories.index', compact('inventories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('inventories.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'price_per_day' => 'required|numeric|min:0|max:999999.99',
            'price_per_week' => 'required|numeric|min:0|max:999999.99',
        ]);

        Inventory::create($request->all());

        return redirect()->route('inventories.index')->with('success', 'Инвентарь успешно добавлен.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Inventory $inventory)
    {
        abort(501, 'Функционал просмотра ещё не разработан.');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Inventory $inventory)
    {
        return view('inventories.edit', compact('inventory'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Inventory $inventory)
    {
        $request->validate([
            'name' => 'required|string|max:255|unique:inventories,name,' . $inventory->id,
            'price_per_day' => 'required|numeric|min:0|max:999999.99',
            'price_per_week' => 'required|numeric|min:0|max:999999.99',
        ]);

        $inventory->update($request->all());

        return redirect()->route('inventories.index')->with('success', 'Информация о инвентаре обновлена.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Inventory $inventory)
    {
        $inventory->delete();

        return redirect()->route('inventories.index')->with('success', 'Инвентарь удален.');
    }
}

resources/views/inventories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4">
        <h1 class="text-2xl font-bold mb-4">Добавить предмет</h1>
        @include('inventories.form', ['action' => route('inventories.store')])
    </div>
@endsection

resources/views/inventories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4">
        <h1 class="text-2xl font-bold mb-4">Редактировать предмет</h1>
        @include('inventories.form', ['action' => route('inventories.update', $inventory->id), 'inventory' => $inventory])
    </div>
@endsection

resources/views/inventories/form.blade.php
<form action="{{ $action }}" method="POST" class="w-full max-w-lg">
    @csrf
    @if(isset($inventory)) @method('PUT') @endif

    <div class="mb-4">
        <label for="name" class="block text-gray-700 text-sm font-bold mb-2">Наименование:</label>
        <input type="text" name="name" id="name" value="{{ $inventory->name ?? '' }}" required class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
    </div>

    <div class="mb-4">
        <label for="price_per_day" class="block text-gray-700 text-sm font-bold mb-2">Цена за сутки:</label>
        <input type="text" name="price_per_day" id="price_per_day" value="{{ $inventory->price_per_day ?? '' }}" required class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
    </div>

    <div class="mb-4">
        <label for="price_per_week" class="block text-gray-700 text-sm font-bold mb-2">Цена за неделю:</label>
        <input type="text" name="price_per_week" id="price_per_week" value="{{ $inventory->price_per_week ?? '' }}" required class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
    </div>

    <div class="mb-4">
        <label for="status" class="block text-gray-700 text-sm font-bold mb-2">Статус:</label>
        <select disabled name="status" id="status" class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            <option value="free" {{ (isset($inventory) && $inventory->status == 'free') ? 'selected' : '' }}>Свободен</option>
            <option value="in_rent" {{ (isset($inventory) && $inventory->status == 'in_rent') ? 'selected' : '' }}>В аренде</option>
        </select>
    </div>

    <div class="flex items-center justify-between">
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Сохранить</button>
    </div>
</form>

resources/views/inventories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4">
        <h1 class="text-2xl font-bold mb-4">Инвентарь</h1>
        <a href="{{ route('inventories.create') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Добавить предмет</a>
        <table class="table-auto w-full mt-4">
            <thead>
            <tr class="bg-gray-200">
                <th class="px-4 py-2">Наименование</th>
                <th class="px-4 py-2">Цена за сутки</th>
                <th class="px-4 py-2">Цена за неделю</th>
                <th class="px-4 py-2">Статус</th>
                <th class="px-4 py-2">Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($inventories as $inventory)
                <tr>
                    <td class="border px-4 py-2">{{ $inventory->name }}</td>
                    <td class="border px-4 py-2">{{ $inventory->price_per_day }}</td>
                    <td class="border px-4 py-2">{{ $inventory->price_per_week }}</td>
                    <td class="border px-4 py-2">{{ $inventory->status == 'in_rent' ? 'В аренде' : 'Свободен' }}</td>
                    <td class="border px-4 py-2 flex justify-around">
                        <a href="{{ route('inventories.edit', $inventory->id) }}" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-1 px-3 rounded">Изменить</a>
                        <form action="{{ route('inventories.destroy', $inventory->id) }}" method="POST" onsubmit="return confirm('Вы уверены, что хотите удалить этот предмет?');">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-3 rounded">Удалить</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection