routes/web.php
<?php

use App\Http\Controllers\AnalyticController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\RentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('inventories/available', [RentController::class, 'getAvailableInventoriesAjax'])->name('inventories.available');

Route::resource('employees', EmployeeController::class);
Route::resource('clients', ClientController::class);
Route::resource('inventories', InventoryController::class);
Route::resource('rents', RentController::class);

Route::get('analytic/rents', [AnalyticController::class, 'rents'])->name('analytic.rents');
Route::get('analytic/employees', [AnalyticController::class, 'employees'])->name('analytic.employees');

app/Models/Rent.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Rent extends Model
{
    use HasFactory;

    protected $fillable = [
        'employee_id',
        'client_id',
        'inventory_id',
        'start_date',
        'end_date',
        'total_cost',
        'status'
    ];

    public function employee() :BelongsTo
    {
        return $this->belongsTo(Employee::class);
    }

    public function client() :BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    public function inventory() :BelongsTo
    {
        return $this->belongsTo(Inventory::class);
    }
}

app/Http/Controllers/RentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RentRequest;
use App\Models\Client;
use App\Models\Employee;
use App\Models\Inventory;
use App\Models\Rent;
use Illuminate\Http\Request;

class RentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $rents = Rent::with(['employee', 'client', 'inventory'])->get();
        return view('rents.index', compact('rents'));
    }

    public function create()
    {
        return view('rents.create', [
            'employees' => Employee::all(),
            'clients' => Client::all(),
            'inventories' => $this->getAvailableInventories(),
        ]);
    }

    public function store(RentRequest $request)
    {
        Rent::create($request->all());

        return redirect()->route('rents.index')->with('success', 'Аренда успешно добавлена.');
    }

    public function show(Rent $rent)
    {
        abort(501, 'Функционал просмотра ещё не разработан.');
    }


    public function edit(Rent $rent)
    {
        return view('rents.edit', [
            'rent' => $rent,
            'employees' => Employee::all(),
            'clients' => Client::all(),
            'inventories' => $this->getAvailableInventories($rent),
        ]);
    }


    public function update(/*RentRequest $request,*/ Rent $rent)
    {
//        $rent->update($request->all());
        $rent->status = "closed";
        $rent->save();

        return redirect()->route('rents.index')->with('success', 'Информация об аренде обновлена.');
    }


    public function destroy(Rent $rent)
    {
        $rent->delete();

        return back()->with('success', 'Аренда удалена.');
    }

    public function getAvailableInventoriesAjax(Request $request)
    {
        $rentId = $request->input('rent_id');
        $rent = $rentId ? Rent::find($rentId) : null;

        $inventories = $this->getAvailableInventories($rent);

        return response()->json($inventories);
    }

    private function getAvailableInventories(Rent $rent = null)
    {
        $query = Inventory::query();

        if ($rent) {
            $query->whereDoesntHave('rents', function ($query) use ($rent) {
                $query->where('status', 'active')->where('id', '!=', $rent->id);
            })->orWhere('id', $rent->inventory_id);
        } else {
            $query->doesntHave('rents', 'and', function ($query) {
                $query->where('status', 'active');
            });
        }

        return $query->get();
    }
}

resources/views/rents/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4">
        <h1 class="text-2xl font-bold mb-4">Добавить аренду</h1>
        @include('rents.form', ['action' => route('rents.store')])
    </div>
    @push('scripts')
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                const calculateEndDateAndTotalCost = () => {
                    const tariffType = document.getElementById('tariff_type').value;
                    const duration = parseInt(document.getElementById('duration').value, 10) || 0;
                    const startDate = document.getElementById('start_date').value;
                    const inventoryId = document.getElementById('inventory_id').value;
                    const inventoryOption = document.querySelector(`#inventory_id option[value="${inventoryId}"]`);
                    let endDate = new Date(startDate);
                    let totalCost = 0;

                    let pricePerDay = 0;
                    let pricePerWeek = 0;

                    if (inventoryOption) {
                        pricePerDay = parseFloat(inventoryOption.dataset.pricePerDay) || 0;
                        pricePerWeek = parseFloat(inventoryOption.dataset.pricePerWeek) || 0;
                    }

                    if (tariffType === 'daily') {
                        endDate.setDate(endDate.getDate() + duration);
                        totalCost = pricePerDay * duration;
                    } else if (tariffType === 'weekly') {
                        endDate.setDate(endDate.getDate() + (duration * 7));
                        totalCost = pricePerWeek * duration;
                    }

                    document.getElementById('end_date').valueAsDate = endDate;
                    document.getElementById('total_cost').value = totalCost.toFixed(2);
                };

                const elements = ['tariff_type', 'duration', 'start_date', 'inventory_id'];

                elements.forEach((element) => {
                    document.getElementById(element).addEventListener('change', calculateEndDateAndTotalCost);
                    document.getElementById(element).addEventListener('input', calculateEndDateAndTotalCost);
                });

                calculateEndDateAndTotalCost();
            });

        </script>
    @endpush
@endsection

resources/views/rents/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4">
        <h1 class="text-2xl font-bold mb-4">Редактировать аренду</h1>
        @include('rents.form', ['action' => route('rents.update', $rent->id), 'rent' => $rent])
    </div>
@endsection

resources/views/rents/form.blade.php
@if(isset($rent))
    <form action="{{ route('rents.update', $rent->id) }}" method="POST" class="w-full max-w-lg">
        @method('PUT')
        @else
            <form action="{{ route('rents.store') }}" method="POST" class="w-full max-w-lg">
                @endif
                @csrf

                <div class="mb-4">
                    <label for="employee_id" class="block text-gray-700 text-sm font-bold mb-2">Сотрудник:</label>
                    <select name="employee_id" id="employee_id" required
                            class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                        @foreach($employees as $employee)
                            <option
                                value="{{ $employee->id }}" {{ (isset($rent) && $rent->employee_id == $employee->id) ? 'selected' : '' }}>
                                {{ $employee->name }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="mb-4">
                    <label for="client_id" class="block text-gray-700 text-sm font-bold mb-2">Клиент:</label>
                    <select name="client_id" id="client_id" required
                            class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                        @foreach($clients as $client)
                            <option
                                value="{{ $client->id }}" {{ (isset($rent) && $rent->client_id == $client->id) ? 'selected' : '' }}>
                                {{ $client->name }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="mb-4">
                    <label for="inventory_id" class="block text-gray-700 text-sm font-bold mb-2">Инвентарь:</label>
                    <select name="inventory_id" id="inventory_id" required
                            class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                            <option value="">
                                *Не выбрано*
                            </option>
                    </select>
                </div>

                <div class="mb-4">
                    <label for="tariff_type" class="block text-gray-700 text-sm font-bold mb-2">Тип аренды:</label>
                    <select name="tariff_type" id="tariff_type" required
                            class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                        <option value="daily">Посуточно</option>
                        <option value="weekly">Понедельно</option>
                    </select>
                </div>

                <div class="mb-4">
                    <label for="duration" class="block text-gray-700 text-sm font-bold mb-2">Количество
                        дней/недель:</label>
                    <input type="number" name="duration" id="duration" required
                           class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                           min="1" value="1">
                </div>

                <div class="mb-4">
                    <label for="start_date" class="block text-gray-700 text-sm font-bold mb-2">Дата начала:</label>
                    <input type="date" name="start_date" id="start_date" value="{{ $rent->start_date ?? '' }}" required
                           class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                </div>

                <div class="mb-4">
                    <label for="end_date" class="block text-gray-700 text-sm font-bold mb-2">Дата окончания:</label>
                    <input type="date" name="end_date" id="end_date" value="{{ $rent->end_date ?? '' }}"
                           readonly
                           class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                </div>

                <div class="mb-4">
                    <label for="total_cost" class="block text-gray-700 text-sm font-bold mb-2">Общая стоимость:</label>
                    <input type="text" name="total_cost" id="total_cost" value="{{ $rent->total_cost ?? '' }}" required
                           readonly
                           class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                </div>

                <div class="mb-4">
                    <label for="status" class="block text-gray-700 text-sm font-bold mb-2">Статус:</label>
                    <select name="status" id="status" required
                            class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                        <option value="active" {{ (isset($rent) && $rent->status == 'active') ? 'selected' : '' }}>
                            Активна
                        </option>
                        <option value="closed" {{ (isset($rent) && $rent->status == 'closed') ? 'selected' : '' }}>
                            Закрыта
                        </option>
                    </select>
                </div>

                <div class="flex items-center justify-between">
                    <button type="submit"
                            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Сохранить
                    </button>
                </div>
                @push('scripts')
                    <script>
                        document.addEventListener('DOMContentLoaded', function() {
                            axios.get('{{ route("inventories.available") }}')
                                .then(function(response) {
                                    const data = response.data;
                                    const select = document.getElementById('inventory_id');
                                    select.disabled;

                                    data.forEach(function(inventory) {
                                        const option = document.createElement('option');
                                        option.value = inventory.id;
                                        option.textContent = inventory.name;
                                        option.dataset.pricePerDay = inventory.price_per_day;
                                        option.dataset.pricePerWeek = inventory.price_per_week;
                                        select.appendChild(option);
                                    });
                                    select.enabled;
                                })
                                .catch(function(error) {
                                    console.log(error);
                                });
                        });
                    </script>

                @endpush
            </form>

resources/views/rents/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4">
        <h1 class="text-2xl font-bold mb-4">Аренды</h1>
        <a href="{{ route('analytic.rents') }}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Аналитика</a>
        <a href="{{ route('rents.create') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Добавить аренду</a>
        <table class="table-auto w-full mt-4">
            <thead>
            <tr class="bg-gray-200">
                <th class="px-4 py-2">Сотрудник</th>
                <th class="px-4 py-2">Клиент</th>
                <th class="px-4 py-2">Инвентарь</th>
                <th class="px-4 py-2">Дата начала</th>
                <th class="px-4 py-2">Дата окончания</th>
                <th class="px-4 py-2">Стоимость</th>
                <th class="px-4 py-2">Статус</th>
                <th class="px-4 py-2">Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($rents as $rent)
                <tr>
                    <td class="border px-4 py-2">{{ $rent->employee->name }}</td>
                    <td class="border px-4 py-2">{{ $rent->client->name }}</td>
                    <td class="border px-4 py-2">{{ $rent->inventory->name }}</td>
                    <td class="border px-4 py-2">{{ $rent->start_date }}</td>
                    <td class="border px-4 py-2">{{ $rent->end_date ?? 'Не указано' }}</td>
                    <td class="border px-4 py-2">{{ $rent->total_cost }}</td>
                    <td class="border px-4 py-2">
                        {{ $rent->status == 'active' ? 'Активна' : 'Закрыта' }}
                    </td>
                    <td class="border px-4 py-2 flex justify-around">
                        @if ($rent->status === 'active')
                            <form action="{{ route('rents.update', $rent->id) }}" method="POST" onsubmit="return confirm('Вы уверены, что хотите ЗАКРЫТЬ эту аренду?');">
                                @csrf
                                @method('PUT')
                                <button type="submit"
                                        class="bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-3 rounded">
                                    Закрыть
                                </button>
                            </form>
                        @endif
                        <form action="{{ route('rents.destroy', $rent->id) }}" method="POST" onsubmit="return confirm('Вы уверены, что хотите УДАЛИТЬ эту аренду?');">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-3 rounded">Удалить</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection